import Head from "next/head";
import Link from "next/link";
import JoinSociety from "~/components/joinSociety";

// import { api } from "~/utils/api";

export default function Dummy() {
  //   const data = api.room.getRoomStatus.useQuery({ roomId: 2 });

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        <>Testing</>
        <JoinSociety />
      </main>
    </>
  );
}