import Head from "next/head";
import Link from "next/link";

// import { api } from "~/utils/api";

export default function Leaderboard() {

  return (
    <>
      <Head>
        <title>Leaderboard</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        Hello
      </main>
    </>
  );
}